name: Selenium Java CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest # Using linux machine

    steps:
    - uses: actions/checkout@v1 # Checkout the code
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1 # Setup JAVA
      with:
        java-version: 1.8
    - name: Install Google Chrome # Using shell script to install Google Chrome
      run: |
        wget --no-verbose -O /tmp/chrome.deb http://dl.google.com/linux/chrome/deb/pool/main/g/google-chrome-stable/google-chrome-stable_87.0.4280.66-0ubuntu0.16.04.1_amd64.deb \
        && apt install -y /tmp/chrome.deb \
        && rm /tmp/chrome.de
    - name: Build with Maven
      run: mvn verify --file pom.xml
